name: bookstore_flutter
description: BookStore mobile & web app with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.0
  http_parser: ^4.0.2
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
